#ifndef __GUIMyFrame1__
#define __GUIMyFrame1__

/**
@file
Subclass of MyFrame1, which is generated by wxFormBuilder.
*/

#include "GUI.h"

//// end generated include
#include <wx/dcbuffer.h> 

#define EPSILON 0.000001

/** Implementing MyFrame1 */
class GUIMyFrame1 : public MyFrame1
{
	protected:
		// Handlers for MyFrame1 events.
		void UpdateUI( wxUpdateUIEvent& event );
		void m_button1_click( wxCommandEvent& event );
		void m_button2_click( wxCommandEvent& event );
		void m_button3_click( wxCommandEvent& event );
		void m_button4_click( wxCommandEvent& event );
		void m_cb_color_click( wxCommandEvent& event );
		void m_s_rotation_onscroll( wxScrollEvent& event );
		void m_s_tilt_onscroll( wxScrollEvent& event );
	public:
		/** Constructor */
		GUIMyFrame1( wxWindow* parent );
	//// end generated class members
		void Repaint();
		bool IsColor;
		int function_number;
		float FunctionData[100][3];
		int   NoPoints;
		void PrepareData(int fun);
		float Shepard(int N, float d[][3], float x, float y);
		float Data[500][500];
		float mini_value;
		float max_value;
		void VoxelSpace(float Xcor, float Ycor, float high, float horizon, float high_scale, wxColor color, wxBufferedDC & dc);
		wxColor PickColor(float high);
		void PreperPoints();
		void RotatePoints(double alfa);
};

#endif // __GUIMyFrame1__
